export const subThemeDef: Record<string,string> = {
  Survival: "It's about staying alive and dealing with tough situations and choices.",
  Disaster: "Crisis and aftermath reshape characters or society.",
  Abandonment: "The emotional struggle or consequences of being left behind or deserted.",
  Acceptance: "Learning to embrace reality, oneself, or others despite difficulties.",
  Achievement: "The pursuit of goals, success, or personal accomplishment.",
  Addiction: "The struggle with dependency and its impact on life and relationships.",
  Adversity: "Overcoming challenges, hardships, and obstacles.",
  Alienation: "Feeling disconnected, isolated, or estranged from others or society.",
  Appearance: "The significance of physical looks and their impact on perception.",
  Authority: "The use, abuse, or challenge of power and control over others.",
  Beauty: "The appreciation and impact of aesthetic value in life and art.",
  Change: "Transformation, adaptation, and the evolution of circumstances.",
  Childhood: "The innocence, wonder, and formative experiences of youth.",
  Choice: "The weight and consequences of decisions and free will.",
  Class: "Social hierarchy, economic disparity, and their effects on individuals.",
  Communication: "The importance and challenges of expressing oneself effectively.",
  Competition: "Rivalry, contests, and the drive to outperform others.",
  Conformity: "The pressure to fit in versus the desire for individuality.",
  Connection: "The human need for relationships and meaningful bonds.",
  Courage: "Bravery in the face of fear, danger, or adversity."
};